# Generated by Django 5.0.1 on 2024-02-07 10:17

import appbackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0002_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=appbackend.models.upload_image_path),
        ),
    ]
